steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/boston-luxury-re-producer', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/boston-luxury-re-producer']

images:
- 'gcr.io/${PROJECT_ID}/boston-luxury-re-producer'
