// This file is auto-generated by Convex
// Placeholder for TypeScript to resolve imports
// Run `npx convex dev` to generate the real file

import { anyApi } from "convex/server";

export const api = anyApi as any;
export const internal = anyApi as any;
