// This file is auto-generated by Convex
// Placeholder for TypeScript to resolve imports

import { FunctionReference } from "convex/server";

export declare const api: {
  videos: {
    createJob: FunctionReference<"mutation">;
    updateProgress: FunctionReference<"mutation">;
    complete: FunctionReference<"mutation">;
    setError: FunctionReference<"mutation">;
    get: FunctionReference<"query">;
    listByUser: FunctionReference<"query">;
    getRecent: FunctionReference<"query">;
    getActive: FunctionReference<"query">;
    remove: FunctionReference<"mutation">;
  };
  users: {
    upsert: FunctionReference<"mutation">;
    getByClerkId: FunctionReference<"query">;
    updatePlan: FunctionReference<"mutation">;
    useCredits: FunctionReference<"mutation">;
    addCredits: FunctionReference<"mutation">;
  };
  insights: {
    create: FunctionReference<"mutation">;
    listByUser: FunctionReference<"query">;
    get: FunctionReference<"query">;
    remove: FunctionReference<"mutation">;
  };
  agentProfiles: {
    getByUser: FunctionReference<"query">;
    upsert: FunctionReference<"mutation">;
  };
};
