/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by Convex
// Placeholder for TypeScript to resolve imports
// Run `npx convex dev` to generate the real file

import type { QueryBuilder, MutationBuilder, ActionBuilder } from "convex/server";

export declare const query: QueryBuilder<any, "public">;
export declare const mutation: MutationBuilder<any, "public">;
export declare const action: ActionBuilder<any, "public">;
export declare const internalQuery: QueryBuilder<any, "internal">;
export declare const internalMutation: MutationBuilder<any, "internal">;
export declare const internalAction: ActionBuilder<any, "internal">;
