/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by Convex
// Placeholder for TypeScript to resolve imports
// Run `npx convex dev` to generate the real file

import {
  QueryBuilder,
  MutationBuilder,
  ActionBuilder,
} from "convex/server";

// Placeholder function builders - will be replaced by generated code
export const query = ((fn: any) => fn) as unknown as QueryBuilder<any, "public">;
export const mutation = ((fn: any) => fn) as unknown as MutationBuilder<any, "public">;
export const action = ((fn: any) => fn) as unknown as ActionBuilder<any, "public">;
export const internalQuery = ((fn: any) => fn) as unknown as QueryBuilder<any, "internal">;
export const internalMutation = ((fn: any) => fn) as unknown as MutationBuilder<any, "internal">;
export const internalAction = ((fn: any) => fn) as unknown as ActionBuilder<any, "internal">;
