// This file is auto-generated by Convex
// Placeholder for TypeScript to resolve imports
// Run `npx convex dev` to generate the real file

export { query, mutation, internalQuery, internalMutation, action, internalAction } from "convex/server";
